

server:
  port: 443
  ssl:
    key-store: classpath:1616293_cangwu.art.pfx
    key-store-type: PKCS12
    key-store-password: 7tAharMC
spring:
  application:
    name: flag-base
  data:
    mongodb:
      host: 47.107.108.68
      port: 27017
      database: flag-base



